# Generated by Django 2.1.7 on 2019-03-08 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('is_enabled', models.BooleanField(blank=True, default=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('mfa_enabled', models.BooleanField(blank=True, default=False)),
                ('mfa_secret', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'users',
                'default_related_name': 'users',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('common_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('platform', models.CharField(default='', max_length=32)),
                ('remote_ip', models.CharField(max_length=32)),
                ('virtual_ip', models.CharField(db_index=True, max_length=32, unique=True)),
            ],
            options={
                'db_table': 'clients',
                'default_related_name': 'client',
                'ordering': ('virtual_ip',),
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint', models.CharField(blank=True, db_index=True, max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=18)),
                ('serial', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devices',
                'default_related_name': 'devices',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detail', models.TextField(default='')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
                'default_related_name': 'events',
                'ordering': ('-created_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('destination', models.CharField(blank=True, default='', max_length=255)),
                ('is_enabled', models.BooleanField(blank=True, default=True)),
                ('port', models.CharField(blank=True, default='', max_length=255)),
                ('protocol', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'firewall_rules',
                'default_related_name': 'firewall_rules',
                'ordering': ('-action',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_enabled', models.BooleanField(blank=True, default=True)),
                ('max_devices', models.IntegerField(blank=True, default=1)),
                ('name', models.CharField(db_index=True, max_length=32, unique=True)),
            ],
            options={
                'db_table': 'groups',
                'default_related_name': 'groups',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RevokedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'revoked_devices',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'setting',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewall_rules', to='common.Group'),
        ),
        migrations.AddField(
            model_name='client',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='common.Device'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='common.Group'),
        ),
    ]
