# Generated by Django 2.1.7 on 2019-03-28 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190321_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'default_related_name': 'devices', 'ordering': ('created_at',)},
        ),
    ]
