# Generated by Django 2.1.7 on 2019-03-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190328_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='mfa_enforced',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_enforced',
            field=models.NullBooleanField(default=None),
        ),
    ]
