# Generated by Django 2.1.7 on 2019-03-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20190331_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_change',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password_expire',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
