verb {{ .LogLevel }}
script-security 3
dev tun0
dev-type tun
persist-tun
persist-key
tls-server
proto {{ .Protocol }}
{{ if and .PortShare (eq .Protocol "tcp") }}
port-share 127.0.0.1 {{ .PortShare }}
{{ end }}
{{ if and .MSSFix (eq .Protocol "udp") }}
mssfix {{ .MSSFix }}
{{ end }}
{{ if eq .Protocol "udp" }}
fast-io
{{ end }}
keepalive 10 30
ping-timer-rem
local {{ .BindAddress }}
lport {{ .BindPort }}
server {{ .Plan.Network.Addr }} {{ .Plan.Mask }} nopool
ifconfig-pool {{ .Plan.PoolStart }} {{ .Plan.PoolEnd }} {{ .Plan.Mask }}
topology subnet
data-ciphers AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305
tls-version-min 1.2
allow-compression no
auth SHA512
auth-gen-token {{ .SessionLifetime }}
log {{ .LogFile }}
status {{ .StatusFile }} 10
status-version 2
management {{ .ManagementSocket }} unix
key-direction 0
dh none
crl-verify {{ .CRLFile }}

auth-user-pass-verify "{{ .Executable }} vpn client-authenticate" via-env
client-connect "{{ .Executable }} vpn client-connect"
client-disconnect "{{ .Executable }} vpn client-disconnect"
{{ if .RedirectGateway }}
push "redirect-gateway def1"
{{ end }}
{{- range .Nameservers }}
push "dhcp-option DNS {{ . }}"
push "route {{ . }}"
{{- end }}
{{ if .Domain }}
push "dhcp-option DOMAIN {{ .Domain }}"
{{ end }}
{{- range .Routes }}
push "route {{ expandCIDR . }}"
{{- end }}

<ca>
{{ .CACertificate }}
</ca>
<cert>
{{ .Certificate }}
</cert>
<key>
{{ .PrivateKey }}
</key>
<tls-auth>
{{ .TLSAuthKey }}
</tls-auth>
